### ISSUE TITLE
handle not working

### ISSUE THREAD

**Issue by anzem** [bmartinson/ngx-draggable-dom#30]
```
<div class="element" [ngxDraggableDom]="true" [handle]="handle" [bounds]="bounds" [constrainByBounds]="true">
   <div class="handle" #handle></div>
</div>
```

_Property 'handle' is private and only accessible within class 'NgxDraggableDomDirective'._

Also is there a way to have multiple draggable elements with handle?

**Comment by happyfeet1996** [comment]
same problem

**Comment by bmartinson** [comment]
Hey @anzem and @happyfeet1996 - thanks for pointing this out. In older versions of Angular, it used to be the case that you could still access data bound properties via templates while keeping them privately accessible - to disallow programmatic access or manipulation outside of ng lifecycle hooks. Newer versions of Angular require they be publicly accessible - I'll get a fix out to unblock you ASAP. @anzem I'll have some updates and answers to your second question shortly as well.

Thanks for your patience!

**Comment by bmartinson** [comment]
Hi, @anzem and @happyfeet1996, please see release 2.4.6 to resolve this issue. Let me know if you need further support or have any other requests.

As for a single handle to manage a grouping of elements, note that a handle must be a child element of the overall draggable content. This is because of the use HostListener to capture events. Since a single handle to control a set of elements would need to move them all relative to their current positioning, it makes sense to use a parent container to group them and apply the directive there. See https://github.com/bmartinson/ngx-draggable-dom/blob/master/src/app/app.component.html#L25-L59 for an example of two elements, each with handles to control each of them, and a third handle to control the group of them. I believe this is exactly what you'd be looking for. If you want the elements included dynamically, consider programmatically detaching and re-attaching the elements to the DOM tree where needed. Or dynamically destroying/creating components if in the ng lifecycle.

Hope this helps, @anzem!
